source:
  path: ..

package:
  name: microdrop_ext_libs
  version: 0.2.alpha

build:
  script:
   - python setup.py install --single-version-externally-managed --record record.txt

requirements:
 build:
  - python
  - pip
  - path-helpers

about:
 home: https://github.com/Vigne-hub/microdrop_ext_libs
 license: BSD

